"""Add Categoria model with self-referential FK

Revision ID: 194f6eb2a0cb
Revises: 497611b4a0c1
Create Date: 2026-05-18 19:43:23.123081

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "194f6eb2a0cb"
down_revision: str | Sequence[str] | None = "497611b4a0c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categoria",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("soft_deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categoria.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_categoria_parent", "categoria", ["parent_id"], unique=False)
    op.create_index(op.f("ix_categoria_nombre"), "categoria", ["nombre"], unique=True)
    op.create_index(
        op.f("ix_categoria_soft_deleted_at"), "categoria", ["soft_deleted_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_categoria_soft_deleted_at"), table_name="categoria")
    op.drop_index(op.f("ix_categoria_nombre"), table_name="categoria")
    op.drop_index("idx_categoria_parent", table_name="categoria")
    op.drop_table("categoria")
    # ### end Alembic commands ###
