"""add_pago_table

Revision ID: 34a1e2321620
Revises: c09d8a9643c9
Create Date: 2026-05-27 11:01:41.143169

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34a1e2321620"
down_revision: str | Sequence[str] | None = "c09d8a9643c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pago",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("pedido_id", sa.UUID(), nullable=False),
        sa.Column("mp_payment_id", sa.String(length=50), nullable=True),
        sa.Column("mp_status", sa.String(length=30), nullable=False),
        sa.Column("external_reference", sa.String(length=100), nullable=False),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("status_detail", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pedido_id"],
            ["pedido.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pago_external_reference"), "pago", ["external_reference"], unique=True)
    op.create_index(op.f("ix_pago_idempotency_key"), "pago", ["idempotency_key"], unique=True)
    op.create_index(op.f("ix_pago_mp_payment_id"), "pago", ["mp_payment_id"], unique=True)
    op.create_index(op.f("ix_pago_pedido_id"), "pago", ["pedido_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pago_pedido_id"), table_name="pago")
    op.drop_index(op.f("ix_pago_mp_payment_id"), table_name="pago")
    op.drop_index(op.f("ix_pago_idempotency_key"), table_name="pago")
    op.drop_index(op.f("ix_pago_external_reference"), table_name="pago")
    op.drop_table("pago")
    # ### end Alembic commands ###
