"""add producto, producto_categoria, producto_ingrediente models

Revision ID: 35a05988bc32
Revises: c55383006cf6
Create Date: 2026-05-20 10:51:10.620735

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35a05988bc32"
down_revision: str | Sequence[str] | None = "c55383006cf6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "producto",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=200), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("precio_base", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("stock_cantidad", sa.Integer(), nullable=False),
        sa.Column("disponible", sa.Boolean(), nullable=False),
        sa.Column("imagen_url", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("soft_deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_producto_soft_deleted_at"), "producto", ["soft_deleted_at"], unique=False
    )
    op.create_table(
        "producto_categoria",
        sa.Column("producto_id", sa.UUID(), nullable=False),
        sa.Column("categoria_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["categoria_id"],
            ["categoria.id"],
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["producto.id"],
        ),
        sa.PrimaryKeyConstraint("producto_id", "categoria_id"),
    )
    op.create_table(
        "producto_ingrediente",
        sa.Column("producto_id", sa.UUID(), nullable=False),
        sa.Column("ingrediente_id", sa.UUID(), nullable=False),
        sa.Column("es_removible", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingrediente_id"],
            ["ingrediente.id"],
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["producto.id"],
        ),
        sa.PrimaryKeyConstraint("producto_id", "ingrediente_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("producto_ingrediente")
    op.drop_table("producto_categoria")
    op.drop_index(op.f("ix_producto_soft_deleted_at"), table_name="producto")
    op.drop_table("producto")
    # ### end Alembic commands ###
