"""add_order_tables

Revision ID: c09d8a9643c9
Revises: c178583061c6
Create Date: 2026-05-27 10:33:58.712152

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c09d8a9643c9"
down_revision: str | Sequence[str] | None = "c178583061c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "estado_pedido",
        sa.Column("codigo", sa.String(length=20), nullable=False),
        sa.Column("descripcion", sa.String(length=100), nullable=False),
        sa.Column("orden", sa.Integer(), nullable=False),
        sa.Column("es_terminal", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("codigo"),
    )
    op.create_table(
        "forma_pago",
        sa.Column("codigo", sa.String(length=20), nullable=False),
        sa.Column("descripcion", sa.String(length=100), nullable=False),
        sa.Column("habilitado", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("codigo"),
    )
    op.create_table(
        "pedido",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("usuario_id", sa.UUID(), nullable=False),
        sa.Column("estado_codigo", sa.String(length=20), nullable=False),
        sa.Column("direccion_id", sa.UUID(), nullable=True),
        sa.Column("forma_pago_codigo", sa.String(length=20), nullable=False),
        sa.Column("direccion_snapshot", sa.Text(), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("costo_envio", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("notas", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("soft_deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["direccion_id"], ["direccion_entrega.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["estado_codigo"],
            ["estado_pedido.codigo"],
        ),
        sa.ForeignKeyConstraint(
            ["forma_pago_codigo"],
            ["forma_pago.codigo"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pedido_soft_deleted_at"), "pedido", ["soft_deleted_at"], unique=False)
    op.create_index(op.f("ix_pedido_usuario_id"), "pedido", ["usuario_id"], unique=False)
    op.create_table(
        "detalle_pedido",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("pedido_id", sa.UUID(), nullable=False),
        sa.Column("producto_id", sa.UUID(), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column("precio_snapshot", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("nombre_snapshot", sa.String(length=200), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("personalizacion", postgresql.ARRAY(sa.UUID()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pedido_id"],
            ["pedido.id"],
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["producto.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_detalle_pedido_pedido_id"), "detalle_pedido", ["pedido_id"], unique=False
    )
    op.create_table(
        "historial_estado_pedido",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("pedido_id", sa.UUID(), nullable=False),
        sa.Column("estado_desde", sa.String(length=20), nullable=True),
        sa.Column("estado_nuevo", sa.String(length=20), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("motivo", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pedido_id"],
            ["pedido.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_historial_estado_pedido_pedido_id"),
        "historial_estado_pedido",
        ["pedido_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_historial_estado_pedido_pedido_id"), table_name="historial_estado_pedido"
    )
    op.drop_table("historial_estado_pedido")
    op.drop_index(op.f("ix_detalle_pedido_pedido_id"), table_name="detalle_pedido")
    op.drop_table("detalle_pedido")
    op.drop_index(op.f("ix_pedido_usuario_id"), table_name="pedido")
    op.drop_index(op.f("ix_pedido_soft_deleted_at"), table_name="pedido")
    op.drop_table("pedido")
    op.drop_table("forma_pago")
    op.drop_table("estado_pedido")
    # ### end Alembic commands ###
