"""Add direccion_entrega table

Revision ID: c178583061c6
Revises: 35a05988bc32
Create Date: 2026-05-21 09:08:03.734430

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c178583061c6"
down_revision: str | Sequence[str] | None = "35a05988bc32"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "direccion_entrega",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("usuario_id", sa.UUID(), nullable=False),
        sa.Column("alias", sa.String(length=100), nullable=True),
        sa.Column("calle", sa.String(length=255), nullable=False),
        sa.Column("numero", sa.String(length=20), nullable=False),
        sa.Column("piso", sa.String(length=10), nullable=True),
        sa.Column("departamento", sa.String(length=10), nullable=True),
        sa.Column("ciudad", sa.String(length=100), nullable=False),
        sa.Column("codigo_postal", sa.String(length=20), nullable=False),
        sa.Column("referencia", sa.Text(), nullable=True),
        sa.Column("es_principal", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("soft_deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_direccion_entrega_soft_deleted_at"),
        "direccion_entrega",
        ["soft_deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_direccion_entrega_usuario_id"), "direccion_entrega", ["usuario_id"], unique=False
    )
    op.create_index(
        "ix_direccion_principal_unica",
        "direccion_entrega",
        ["usuario_id", "es_principal"],
        unique=True,
        postgresql_where=sa.text("es_principal = true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_direccion_principal_unica",
        table_name="direccion_entrega",
        postgresql_where=sa.text("es_principal = true"),
    )
    op.drop_index(op.f("ix_direccion_entrega_usuario_id"), table_name="direccion_entrega")
    op.drop_index(op.f("ix_direccion_entrega_soft_deleted_at"), table_name="direccion_entrega")
    op.drop_table("direccion_entrega")
    # ### end Alembic commands ###
