"""Add Ingrediente model

Revision ID: c55383006cf6
Revises: 194f6eb2a0cb
Create Date: 2026-05-18 19:52:44.719321

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c55383006cf6"
down_revision: str | Sequence[str] | None = "194f6eb2a0cb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingrediente",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("es_alergeno", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("soft_deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ingrediente_nombre"), "ingrediente", ["nombre"], unique=True)
    op.create_index(
        op.f("ix_ingrediente_soft_deleted_at"), "ingrediente", ["soft_deleted_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ingrediente_soft_deleted_at"), table_name="ingrediente")
    op.drop_index(op.f("ix_ingrediente_nombre"), table_name="ingrediente")
    op.drop_table("ingrediente")
    # ### end Alembic commands ###
